version: '3.9'
services:
  web:
    container_name: kost-payment-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
